nodeLinker: node-modules

npmRegistryServer: "http://verdaccio.mw.local"
npmPublishRegistry: "http://verdaccio.mw.local"

npmAlwaysAuth: false

npmRegistries:
  "http://verdaccio.mw.local":
    npmAlwaysAuth: false

npmScopes:
  plugger:
    npmRegistryServer: "http://verdaccio.mw.local"
    npmPublishRegistry: "http://verdaccio.mw.local"
    npmAlwaysAuth: false